import { Course } from './course.model';

export class Semester {
    year: number;
    session: string;
    courses: Course[] = [];
    id: number; // auto generated by db

    constructor(json: any) {
        if (json.year) this.year = json.year;
        if (json.session) this.session = json.session;
        if (json.id != null) {
            this.id = json.id;
        }
        if (json.courses) {
            json.courses.forEach((course) => {
                this.courses.push(new Course(course));
            });
        }

    }

    get hours() {
        let hours = 0;
        this.courses.forEach((course) => {
            hours += Number(course.hours);
        });
        return hours;
    }

    get gpa() {
        let hours: number = 0;
        let points: number = 0;
        this.courses.forEach((course) => {
            hours += Number(course.hours);
            points += course.numberGrades()*course.hours;
        });
        let total = points/hours;
        return total; 
    }
}