import { Component, OnInit } from '@angular/core';
import { GradeReceiverService } from '../../services/grade-receiver.service';
import { Semester } from '../../models/semester.model';
import { Router } from '@angular/router';

@Component({
  selector: 'gt-home-screen', // gt for GradeTracker
  templateUrl: './home-screen.component.html',
  styleUrls: ['./home-screen.component.scss']
})
export class HomeScreenComponent {
  semesters: Semester[] = [];
  errorMessage:string;

  constructor(public GradeReceiver: GradeReceiverService,
              public router: Router) {  }

  ngOnInit() {
    this.getSemesters();
    
  }
  getSemesters(): void {
    this.GradeReceiver.getSemesters().subscribe(data => {
      data.forEach((semester) => {
        this.semesters.push(new Semester(semester));
        
      });
    }, error => this.errorMessage = <any> error);
  }
  navigateToSemesterDetail(id?) {
    this.router.navigate(['/semester/' + id ]); // for autogenerated id from fb
  }

}
