import { Component, OnInit } from '@angular/core';
import { GradeReceiverService } from '../../services/grade-receiver.service';
import { Semester } from '../../models/semester.model';
import { Router } from '@angular/router';

@Component({
  selector: 'gt-home-screen', // gt for GradeTracker
  templateUrl: './home-screen.component.html',
  styleUrls: ['./home-screen.component.css']
})
export class HomeScreenComponent {
  semesters: Semester[] = [];
  errorMessage:string;

  constructor(public GradeReceiver: GradeReceiverService,
              public router: Router) {
    //for(let i=0; i<6; i++)  this.semesters.push(GradeReceiver.getSemesters()); 
  }
  ngOnInit() {
    //Called after the constructor, initializing input properties, and the first call to ngOnChanges.
    //Add 'implements OnInit' to the class.
    this.getSemesters();
    
  }
  getSemesters(): void {
    this.GradeReceiver.getSemesters().subscribe(data => {
                                                  this.semesters = data;
                                                  console.log("Semesters object\n");
                                                  console.log(this.semesters);
                                                  }, error => this.errorMessage = <any> error);
  }
  navigateToSemesterDetail(id?) {
    //this.router.navigate(['/semester/1']);
     this.router.navigate(['/semester/' + id ]); // for autogenerated id from fb
  }

}
